# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('type', models.CharField(choices=[('Condiments', 'Condiments'), ('Oils', 'Cooking oils'), ('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Flour', 'Flour'), ('Additives', 'Food additives'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Herbs', 'Herbs'), ('Meat', 'Meat'), ('Nuts', 'Nuts'), ('Pasta', 'Pasta'), ('Poultry', 'Poultry'), ('Salts', 'Salts'), ('Sauces', 'Sauces'), ('Seafood', 'Seafood'), ('Seeds', 'Seeds'), ('Spices', 'Spices'), ('Sugars', 'Sugars'), ('Vegetables', 'Vegetables')], max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbrev', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
