# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('type', models.CharField(blank=True, choices=[('Bean', 'Bean'), ('Bread', 'Bread'), ('Canned', 'Canned food'), ('Condiment', 'Condiment'), ('Oil', 'Cooking oil'), ('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Flour', 'Flour'), ('Additive', 'Food additive'), ('Fruit', 'Fruit'), ('Grain', 'Grain'), ('Herb', 'Herb'), ('Meat', 'Meat'), ('Nut', 'Nut'), ('Pasta', 'Pasta'), ('Paste', 'Paste'), ('Poultry', 'Poultry'), ('Rice', 'Rice'), ('Salt', 'Salt'), ('Sauce', 'Sauce'), ('Seafood', 'Seafood'), ('Seed', 'Seed'), ('Spice', 'Spice'), ('Sugar', 'Sugar'), ('Unspecified', 'Unspecified'), ('Vegetable', 'Vegetable')], default='Unspecified', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbrev', models.CharField(blank=True, max_length=10, null=True)),
                ('plural', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
