# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
    ]
