# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='plural',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
