# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20160821_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
