# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20170523_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
