# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default='Apple'),
            preserve_default=False,
        ),
    ]
