# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredient',
            name='ingredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient'),
        ),
    ]
