# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 15:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('cuisine', models.CharField(choices=[('us', 'American'), ('au', 'Australian'), ('br', 'Brazilian'), ('cr', 'Caribbean'), ('cn', 'Chinese'), ('ph', 'Filipino'), ('fr', 'French'), ('de', 'German'), ('gr', 'Greek'), ('in', 'Indian'), ('id', 'Indonesian'), ('it', 'Italian'), ('jp', 'Japanese'), ('kr', 'Korean'), ('lb', 'Lebanese'), ('mx', 'Mexican'), ('th', 'Thai'), ('sc', 'Scotland'), ('za', 'South African'), ('es', 'Spanish'), ('ot', 'Other')], default='ot', max_length=2)),
                ('date', models.DateTimeField(editable=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, default='recipes/no-image.jpg', upload_to='recipes/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='ingredients.Ingredient'),
        ),
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('recipe', 'ingredient')]),
        ),
    ]
