# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Additives', 'Food additives'), ('Condiments', 'Condiments'), ('Oils', 'Cooking oils'), ('Eggs', 'Eggs'), ('Dairy', 'Dairy'), ('Flour', 'Flour'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Herbs', 'Herbs'), ('Meat', 'Meat'), ('Nuts', 'Nuts'), ('Pasta', 'Pasta'), ('Poultry', 'Poultry'), ('Salts', 'Salts'), ('Sauces', 'Sauces'), ('Seafood', 'Seafood'), ('Seeds', 'Seeds'), ('Spices', 'Spices'), ('Sugars', 'Sugars'), ('Vegetables', 'Vegetables')], max_length=250)),
            ],
        ),
    ]
