# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170614_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(max_length=3000),
        ),
    ]
