# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/no-image.jpg', upload_to='recipes/'),
        ),
    ]
