# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20160816_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('Condiments', 'Condiments'), ('Oils', 'Cooking oils'), ('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Flour', 'Flour'), ('Additives', 'Food additives'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Herbs', 'Herbs'), ('Meat', 'Meat'), ('Nuts', 'Nuts'), ('Pasta', 'Pasta'), ('Poultry', 'Poultry'), ('Salts', 'Salts'), ('Sauces', 'Sauces'), ('Seafood', 'Seafood'), ('Seeds', 'Seeds'), ('Spices', 'Spices'), ('Sugars', 'Sugars'), ('Vegetables', 'Vegetables')], max_length=250),
        ),
    ]
