# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20160919_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('us', 'American'), ('au', 'Australian'), ('br', 'Brazilian'), ('cr', 'Caribbean'), ('cn', 'Chinese'), ('ph', 'Filipino'), ('fr', 'French'), ('de', 'German'), ('gr', 'Greek'), ('in', 'Indian'), ('id', 'Indonesian'), ('it', 'Italian'), ('jp', 'Japanese'), ('kr', 'Korean'), ('lb', 'Lebanese'), ('mx', 'Mexican'), ('th', 'Thai'), ('sc', 'Scotland'), ('za', 'South African'), ('es', 'Spanish'), ('ot', 'Other')], default='ot', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
