# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160816_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe'),
        ),
    ]
