# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20160818_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Fridge')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fridgeingredient',
            unique_together=set([('fridge', 'ingredient')]),
        ),
    ]
