# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20160919_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('us', 'American'), ('au', 'Australian'), ('br', 'Brazilian'), ('cr', 'Caribbean'), ('cn', 'Chinese'), ('ph', 'Filipino'), ('fr', 'French'), ('de', 'German'), ('gr', 'Greek'), ('in', 'Indian'), ('id', 'Indonesian'), ('it', 'Italian'), ('jp', 'Japanese'), ('kr', 'Korean'), ('lb', 'Lebanese'), ('mx', 'Mexican'), ('th', 'Thai'), ('sc', 'Scotland'), ('za', 'South African'), ('es', 'Spanish'), ('ot', 'Other')], default='ot', max_length=2),
        ),
    ]
