# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20160818_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit'),
        ),
    ]
