# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_fridge_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
